sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

#cache:
#  directories:
#    - "${HOME}/google-cloud-sdk"

env:
  - PATH=${HOME}/google-cloud-sdk/bin:${PATH} GCLOUD_SDK_URL="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-225.0.0-linux-x86_64.tar.gz"

before_install:
  - "[[ -d ${HOME}/google-cloud-sdk ]] || (curl -L ${GCLOUD_SDK_URL} | tar xzf - && mv google-cloud-sdk ${HOME})"
  - openssl aes-256-cbc -K $encrypted_f7e561a24207_key -iv $encrypted_f7e561a24207_iv -in .travis-ci-sa-key.json.enc -out .travis-ci-sa-key.json -d

install:
  - echo -n "${DOCKER_IO_PASSWORD}" | docker login --username ${DOCKER_IO_USERNAME} --password-stdin
  - gcloud --quiet auth activate-service-account --key-file .travis-ci-sa-key.json
  - gcloud --quiet auth configure-docker

script:
  - bash .travis.build.sh

after_script:
  - rm -fv /home/travis/.docker/config.json
