sudo: required

language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - "${HOME}/google-cloud-sdk"

env:
  - PATH=${PATH}:${HOME}/google-cloud-sdk/bin

before_install:
  - openssl aes-256-cbc -K $encrypted_f7e561a24207_key -iv $encrypted_f7e561a24207_iv -in .travis-ci-sa-key.json.enc -out .travis-ci-sa-key.json -d
  - "[[ -d ${HOME}/google-cloud-sdk ]] || curl https://sdk.cloud.google.com | bash"

install:
  - echo -n "${DOCKER_IO_PASSWORD}" | docker login --username ${DOCKER_IO_USERNAME} --password-stdin
  - gcloud auth activate-service-account --key-file .travis-ci-sa-key.json
  - gcloud info
  - gcloud auth configure-docker

script:
  - bash .travis.build.sh

after_script:
  - rm -fv /home/travis/.docker/config.json
