sudo: required

language: bash

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

before_script:
  - echo -n "${DOCKER_IO_PASSWORD}" | docker login --username ${DOCKER_IO_USERNAME} --password-stdin

script:
- bash .travis.build.sh

after_script:
- rm -fv /home/travis/.docker/config.json
