apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: gitzup
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: gitzup
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: gitzup
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - image: gcr.io/gitzup/controller:local
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SECRET_NAME
            value: $(WEBHOOK_SECRET_NAME)
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/serviceaccount-key.json
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
        - mountPath: /secrets
          name: gcp-secret
          readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: webhook-server-secret
          optional: false
      - name: gcp-secret
        secret:
          secretName: gcp-secret
          optional: false
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: gitzup
