apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: ipaddresses.gcp.gitzup.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.ProjectId
    description: Project ID
    name: Project ID
    type: string
  - JSONPath: .spec.NetworkTier
    description: Network Tier
    name: Tier
    type: string
  - JSONPath: .spec.IpVersion
    description: IP version
    name: IP Version
    type: string
  - JSONPath: .spec.Region
    description: Region
    name: Region
    type: string
  - JSONPath: .status.Address
    description: IP address
    name: Address
    type: string
  group: gcp.gitzup.com
  names:
    kind: IpAddress
    plural: ipaddresses
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            ipVersion:
              enum:
              - IPV4
              - IPV6
              type: string
            networkTier:
              enum:
              - PREMIUM
              - STANDARD
              type: string
            projectId:
              pattern: '[a-z][a-z0-9-]{4,28}[a-z0-9]'
              type: string
            region:
              type: string
          required:
          - projectId
          - networkTier
          - ipVersion
          type: object
        status:
          properties:
            Address:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
